#!/bin/bash
# Restore .env files in the rendered modules from the master .env at repo root.
# Run after every `codeplain web.plain` or `codeplain agent.plain`.
#
# Master:  voice-receptionist/.env (gitignored, never re-rendered)
# Targets: plain_modules/web/.env
#          plain_modules/agent/agent/.env

set -eu

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MASTER="$REPO_ROOT/.env"

WEB_TARGET="$REPO_ROOT/plain_modules/web/.env"
AGENT_TARGET="$REPO_ROOT/plain_modules/agent/agent/.env"

if [ ! -f "$MASTER" ]; then
    echo "Error: master .env not found at $MASTER" >&2
    exit 1
fi

# Keys consumed by the web module
WEB_KEYS="DATABASE_URL LIVEKIT_URL LIVEKIT_API_KEY LIVEKIT_API_SECRET PRACTICE_TIMEZONE"

# Keys consumed by the agent module
AGENT_KEYS="LIVEKIT_URL LIVEKIT_API_KEY LIVEKIT_API_SECRET \
DEEPGRAM_API_KEY GOOGLE_API_KEY GEMINI_MODEL \
ELEVENLABS_API_KEY ELEVENLABS_VOICE_ID_FEMALE ELEVENLABS_VOICE_ID_MALE ELEVENLABS_VOICE_ID \
WEB_API_BASE_URL"

# Build a target .env containing only the keys that target needs.
# Lines that don't match a key are skipped; comments and blanks are preserved
# only if they're the master file's header.
write_subset() {
    local target_path="$1"
    shift
    local keys="$*"

    local target_dir
    target_dir="$(dirname "$target_path")"
    if [ ! -d "$target_dir" ]; then
        echo "Skipping $target_path (parent directory does not exist — module not rendered yet)"
        return
    fi

    {
        echo "# Generated by scripts/restore-env.sh from $(realpath --relative-to="$target_dir" "$MASTER" 2>/dev/null || echo "$MASTER")"
        echo "# Do not edit here — edit the master .env at the repo root."
        echo ""
        for key in $keys; do
            line=$(grep -E "^${key}=" "$MASTER" || true)
            if [ -n "$line" ]; then
                echo "$line"
            fi
        done
    } > "$target_path"

    echo "Wrote $target_path"
}

write_subset "$WEB_TARGET" $WEB_KEYS
write_subset "$AGENT_TARGET" $AGENT_KEYS

# Warn about any still-empty values
echo ""
empty_keys=$(grep -E "^[A-Z_]+=$" "$MASTER" | sed 's/=$//' || true)
if [ -n "$empty_keys" ]; then
    echo "Note: the following keys in the master .env are still empty:"
    for k in $empty_keys; do
        echo "  - $k"
    done
    echo "Fill them in $MASTER and re-run this script."
fi
